# Generated by Django 3.1.2 on 2020-10-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KodeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('password', models.TextField(verbose_name='password')),
                ('user_type', models.IntegerField(verbose_name='user_type')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=10)),
            ],
        ),
    ]
