# Generated by Django 3.1.2 on 2020-10-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KODE', '0002_auto_20201028_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.TextField(blank=True, null=True, verbose_name='courier'),
        ),
    ]
