# Generated by Django 3.1.2 on 2020-10-23 19:54

import KODE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KODE', '0003_kodeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kodeuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='kodeuser',
            name='invitation_code',
            field=models.TextField(default=KODE.models.key_gen, verbose_name='invitation_code'),
        ),
    ]
