# Generated by Django 3.1.2 on 2020-10-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KODE', '0004_auto_20201023_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodeuser',
            name='email',
            field=models.CharField(default=None, max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='kodeuser',
            name='password',
            field=models.TextField(default=None, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='kodeuser',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='username'),
        ),
    ]
