# Generated by Django 3.1.2 on 2020-10-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KODE', '0005_auto_20201023_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodeuser',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='kodeuser',
            name='password',
            field=models.TextField(null=True, verbose_name='password'),
        ),
    ]
