# Generated by Django 3.1.2 on 2020-10-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KODE', '0006_auto_20201023_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodeuser',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='kodeuser',
            name='password',
            field=models.TextField(blank=True, verbose_name='password'),
        ),
    ]
