# Generated by Django 3.1.2 on 2020-10-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KODE', '0007_auto_20201023_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='https://mega.nz/file/389GmaQL#OQXKCwFPxAnefvoxmiO5WF6kAlCe3QU76ivJocnNMFQ', null=True, upload_to='', verbose_name='image')),
                ('title', models.TextField(verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
