# Generated by Django 3.1.2 on 2020-10-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KODE', '0008_auto_20201024_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0, verbose_name='count'),
        ),
    ]
