# Generated by Django 3.1.2 on 2020-10-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KODE', '0009_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='name')),
                ('district', models.IntegerField(verbose_name='district')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='', verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1, verbose_name='count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.IntegerField(default=0, verbose_name='courier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.IntegerField(default=0, verbose_name='district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name_of_user',
            field=models.TextField(default='', verbose_name='name_of_user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.TextField(default='', verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.TextField(default='', verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, default='https://mega.nz/file/389GmaQL#OQXKCwFPxAnefvoxmiO5WF6kAlCe3QU76ivJocnNMFQ', null=True, verbose_name='image'),
        ),
    ]
