# Generated by Django 3.1.2 on 2020-10-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KODE', '0010_auto_20201025_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.TextField(verbose_name='courier'),
        ),
    ]
